# Generated by Django 6.0.4 on 2026-05-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='background_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_color',
        ),
    ]
