# Generated by Django 6.0.4 on 2026-05-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_banner_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='background_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='offer_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
