# Generated by Django 6.0.4 on 2026-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_simplify_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.CharField(default='/shop', max_length=200),
        ),
    ]
