# Generated by Django 6.0.4 on 2026-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_banner_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Where Luxury Meets Skin Science', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('overlap_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('auto_generate_text', models.BooleanField(default=True, help_text='Auto-generate premium skincare text if description is empty')),
                ('animation_enabled', models.BooleanField(default=True, help_text='Enable floating and fade-in animations')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for multiple sections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order'],
            },
        ),
    ]
