# Generated by Django 6.0.4 on 2026-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_about_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='brand_tone',
            field=models.CharField(choices=[('premium', 'Premium & Elegant'), ('natural', 'Natural & Organic'), ('clinical', 'Clinical & Scientific'), ('luxury', 'Ultra Luxury')], default='premium', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='product_category',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('anti-aging', 'Anti-Aging'), ('moisturizers', 'Moisturizers'), ('serums', 'Serums'), ('cleansers', 'Cleansers'), ('luxury', 'Luxury Collection')], default='skincare', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='skin_type',
            field=models.CharField(choices=[('all', 'All Skin Types'), ('oily', 'Oily Skin'), ('dry', 'Dry Skin'), ('combination', 'Combination Skin'), ('sensitive', 'Sensitive Skin'), ('normal', 'Normal Skin')], default='oily', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='auto_generate_text',
            field=models.BooleanField(default=True, help_text='Auto-generate heading and description based on selections'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, help_text='Leave empty for auto-generated description'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(blank=True, help_text='Leave empty for auto-generated heading', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
