# Generated by Django 6.0.4 on 2026-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_about_section_auto_generate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='auto_generate_text',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='brand_tone',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='order',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='skin_type',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(default='Discover the art of premium skincare with our meticulously crafted collection. Each product combines advanced dermatological science with luxurious botanical ingredients, delivering visible results that transform your daily routine into an indulgent beauty ritual.'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(default='Where Luxury Meets Skin Science', max_length=250),
        ),
    ]
