# Generated by Django 6.0.4 on 2026-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_update_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
    ]
