# Generated by Django 6.0.4 on 2026-05-08 05:57

from django.db import migrations
from django.utils.text import slugify


def seed_categories(apps, schema_editor):
    Category = apps.get_model('shop', 'Category')
    categories = [
        {'name': 'Lipsticks', 'subtitle': 'Bold, long-lasting colors for every look', 'button_text': 'Shop Lipsticks'},
        {'name': 'Skincare', 'subtitle': 'Nourish and glow with our skincare range', 'button_text': 'Shop Skincare'},
        {'name': 'Eye Makeup', 'subtitle': 'Define your eyes with stunning shades', 'button_text': 'Shop Eye Makeup'},
        {'name': 'Hair Care', 'subtitle': 'Luxurious care for beautiful hair', 'button_text': 'Shop Hair Care'},
        {'name': 'Fragrance', 'subtitle': 'Captivating scents that leave a mark', 'button_text': 'Shop Fragrance'},
        {'name': 'Nails', 'subtitle': 'Perfect nails for every occasion', 'button_text': 'Shop Nails'},
    ]
    for cat in categories:
        Category.objects.get_or_create(
            name=cat['name'],
            defaults={
                'slug': slugify(cat['name']),
                'subtitle': cat['subtitle'],
                'button_text': cat['button_text'],
                'is_active': True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_button_text_category_subtitle_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
