# Generated by Django 6.0.4 on 2026-05-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyGlowifySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Why Glowify', max_length=200)),
                ('subheading', models.CharField(default='Premium skincare crafted for radiant beauty and confidence.', max_length=300)),
                ('model_image', models.ImageField(blank=True, help_text='Upload a beauty model image', null=True, upload_to='whyglowify/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Glowify Section',
                'verbose_name_plural': 'Why Glowify Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='WhyGlowifyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02, 03, 04', max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description for this feature')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.whyglowifysection')),
            ],
            options={
                'verbose_name': 'Why Glowify Feature',
                'verbose_name_plural': 'Why Glowify Features',
                'ordering': ['order'],
            },
        ),
    ]
