# Generated by Django 6.0.4 on 2026-05-08 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_newslettersubscription_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_image', models.ImageField(blank=True, help_text='Upload anime-style beauty girl illustration (left side)', null=True, upload_to='flash_sale/')),
                ('product_image_1', models.ImageField(blank=True, help_text='Serum bottle (right side)', null=True, upload_to='flash_sale/')),
                ('product_image_2', models.ImageField(blank=True, help_text='Lipstick (right side)', null=True, upload_to='flash_sale/')),
                ('product_image_3', models.ImageField(blank=True, help_text='Compact powder (right side)', null=True, upload_to='flash_sale/')),
                ('product_image_4', models.ImageField(blank=True, help_text='Cream tube (right side)', null=True, upload_to='flash_sale/')),
                ('sale_percentage', models.CharField(default='50%', max_length=10)),
                ('heading', models.CharField(default='Glow Confidently every Day', max_length=200)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/shop/', max_length=500)),
                ('enable_sparkles', models.BooleanField(default=True, help_text='Enable sparkle/glow particles around cream jar')),
                ('enable_countdown', models.BooleanField(default=False, help_text='Show countdown timer')),
                ('countdown_end', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flash Sale Banner',
                'verbose_name_plural': 'Flash Sale Banners',
            },
        ),
    ]
