# Generated by Django 6.0.4 on 2026-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_flashsalebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsalebanner',
            name='product_image_1',
        ),
        migrations.RemoveField(
            model_name='flashsalebanner',
            name='product_image_2',
        ),
        migrations.RemoveField(
            model_name='flashsalebanner',
            name='product_image_3',
        ),
        migrations.RemoveField(
            model_name='flashsalebanner',
            name='product_image_4',
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Upload product image (right side)', null=True, upload_to='flash_sale/'),
        ),
    ]
