# Generated by Django 6.0.4 on 2026-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_flashsalebanner_product_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsalebanner',
            name='enable_particles',
            field=models.BooleanField(default=True, help_text='Enable floating background particles'),
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='semi_circle_color_end',
            field=models.CharField(default='#FF69B4', help_text='Semicircle gradient end color (bright pink)', max_length=20),
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='semi_circle_color_start',
            field=models.CharField(default='#FFE4E1', help_text='Semicircle gradient start color (soft blush)', max_length=20),
        ),
        migrations.AddField(
            model_name='flashsalebanner',
            name='subheading',
            field=models.CharField(blank=True, default='Premium beauty essentials for your daily glow', max_length=300),
        ),
    ]
