# Generated by Django 6.0.4 on 2026-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_flashsalebanner_enable_particles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Upload footer background image', null=True, upload_to='footer/')),
                ('bg_color_start', models.CharField(default='#ff4fa3', help_text='Footer gradient start color', max_length=20)),
                ('bg_color_end', models.CharField(default='#ff1493', help_text='Footer gradient end color', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
