# Generated by Django 6.0.4 on 2026-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='address',
            field=models.TextField(default='3rd Floor, Valasaravakam,\nChennai - 600800', help_text='Footer address'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 Glowify. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='#', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='#', help_text='Instagram page URL'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='logo_text',
            field=models.CharField(default='Glowify', help_text='Brand logo text', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_1_text',
            field=models.CharField(default='Shop', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_1_url',
            field=models.CharField(default='/shop/', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_2_text',
            field=models.CharField(default='New Arrivals', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_2_url',
            field=models.CharField(default='/shop/?sort=newest', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_3_text',
            field=models.CharField(default='Offers', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_link_3_url',
            field=models.CharField(default='/offers/', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_1_text',
            field=models.CharField(default='About', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_1_url',
            field=models.CharField(default='/about/', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_2_text',
            field=models.CharField(default='Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_2_url',
            field=models.CharField(default='/contact/', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_3_text',
            field=models.CharField(default='Terms & Conditions', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_3_url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_4_text',
            field=models.CharField(default='Privacy Policy', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_link_4_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
