# Generated by Django 6.0.4 on 2026-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_footersettings_address_footersettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='facebook_url',
            field=models.CharField(blank=True, default='#', help_text='Facebook page URL', max_length=200),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.CharField(blank=True, default='#', help_text='Instagram page URL', max_length=200),
        ),
    ]
