# Generated by Django 6.0.4 on 2026-05-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_haircareproduct_lipstickproduct_nailproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkincareProduct',
        ),
    ]
