# Generated by Django 6.0.4 on 2026-05-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_delete_skincareproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload offers page banner image (1920x700 recommended)', null=True, upload_to='offers/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offer Banner',
                'verbose_name_plural': 'Offer Banners',
                'ordering': ['order'],
            },
        ),
    ]
