# Generated by Django 6.0.4 on 2026-05-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_offerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidnightSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midnight_set/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Midnight Set',
                'verbose_name_plural': 'Midnight Sets',
            },
        ),
    ]
