# Generated by Django 6.0.4 on 2026-05-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_midnightset'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload newsletter left side image', upload_to='newsletter/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Image',
                'verbose_name_plural': 'Newsletter Images',
            },
        ),
    ]
