# Generated by Django 6.0.4 on 2026-05-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_newsletterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Upload background image for the hero banner', upload_to='about_hero/')),
                ('title', models.CharField(default='The Art of Radiant Skin', max_length=200)),
                ('subtitle', models.TextField(default='The legacy of timeless beauty and scientific precision, crafted for the modern connoisseur')),
                ('button_text', models.CharField(default='Explore Collection', max_length=100)),
                ('button_url', models.CharField(blank=True, default='#', max_length=500)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.15, help_text='Overlay opacity (0.00 to 1.00)', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Hero Banner',
                'verbose_name_plural': 'About Hero Banners',
            },
        ),
    ]
