# Generated by Django 6.0.4 on 2026-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_aboutherobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_right/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Right Image',
                'verbose_name_plural': 'About Right Images',
                'ordering': ['order'],
            },
        ),
    ]
