# Generated by Django 6.0.4 on 2026-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_aboutrightimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload founder portrait image', upload_to='founder/')),
                ('name', models.CharField(default='Elena', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Founder Section',
                'verbose_name_plural': 'Founder Sections',
                'ordering': ['-created_at'],
            },
        ),
    ]
