# Generated by Django 6.0.4 on 2026-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_foundersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Upload contact banner background image (1920x500 recommended)', upload_to='contact_banner/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Banner',
                'verbose_name_plural': 'Contact Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
