# Generated by Django 6.0.4 on 2026-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_contactbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutherobanner',
            name='brightness',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Background image brightness (0.00 to 1.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='brightness',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Background image brightness (0.00 to 1.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Pink overlay opacity (0.00 to 1.00)', max_digits=3),
        ),
    ]
