# Generated by Django 6.0.4 on 2026-05-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_aboutherobanner_brightness_contactbanner_brightness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutherobanner',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='contactbanner',
            name='overlay_opacity',
        ),
    ]
