# Generated by Django 6.0.4 on 2026-05-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_aboutherobanner_brightness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginIllustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload illustration image for login page left side', upload_to='login/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login Illustration',
                'verbose_name_plural': 'Login Illustrations',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
